### ISSUE TITLE
How to set output_image_size when Eval

### ISSUE THREAD

**Issue by dovanchan** [abhiskk/fast-neural-style#14]
Hi
    1、Can you explain what's different of the image_size of "content and style" when Train and Eval?
    2、How to set output_image_size when Eval? (if your default setting is 1080,can you show me where you set in your code?)
    3、Really thanks for your work

**Comment by abhiskk** [comment]
1. The `--image-size` `--style-size` determine the image sizes of content image and style image. They will resize the input images to the value in `--image-size` and `--style-size` parameters.
2. The output image size will be same as the input image size by default, if you are feeding in a really large image then I have added a command line parameter [here](https://github.com/abhiskk/fast-neural-style/blob/master/neural_style/neural_style.py#L183-L184) , using which you can reduce the size of the output styled image, for eg setting `--content-scale` will produce an output image which is half the size of the input image.
3. 😃

**Comment by dovanchan** [comment]
If I wanna use it to make a ios app like prisma in production enviroment,Can you give me some advices for reducing memory usage.I found pytorch's implement is better than tensorflow in fast-neural-style

**Comment by abhiskk** [comment]
I would suggest looking into using Caffe2 for that. You should be able to load the pytorch model in Caffe2 directly, you will have to convert weights to numpy and then load it in Caffe2. Then I think you can follow this [tutorial](https://caffe2.ai/docs/AI-Camera-demo-android) to build an app for that.

**Comment by dovanchan** [comment]
When I try eval,I get a error(python2.7)

Dovan-Rmbp:fast-neural-style DOVAN$ time python neural_style/neural_style.py eval --content-image /Users/DOVAN/Desktop/WX20170621-141545@2x.png --model /Users/DOVAN/deeprely/fast-neural-style/saved-models/udnie.pth --output-image /Users/DOVAN/Desktop/ --cuda 0
Traceback (most recent call last):
  File "neural_style/neural_style.py", line 210, in <module>
    main()
  File "neural_style/neural_style.py", line 206, in main
    stylize(args)
  File "neural_style/neural_style.py", line 135, in stylize
    content_image = Variable(utils.preprocess_batch(content_image), volatile=True)
  File "/Users/DOVAN/deeprely/fast-neural-style/neural_style/utils.py", line 59, in preprocess_batch
    (r, g, b) = torch.chunk(batch, 3)
ValueError: need more than 2 values to unpack

Can you tell me how to fix it

**Comment by abhiskk** [comment]
I just tested the implementation again on python 2.7 and it works. Can you try and install pytorch again in a clean environment using conda following the instructions from the [pytorch site](http://pytorch.org/).

**Comment by abhiskk** [comment]
Actually I think it's an issue with loading `.png` images, I think it will work well for `.jpg` images. Similar issue was reported on the pytorch/examples version of this repo.
ref: https://github.com/pytorch/examples/issues/171

**Comment by dovanchan** [comment]
@abhiskk Hi,I have tried the jpg. But I still get this error:

Dovan-Rmbp:fast-neural-style DOVAN$ time python neural_style/neural_style.py eval --content-image /Users/DOVAN/Desktop/WX20170621-141545@2x.jpg --model /Users/DOVAN/deeprely/fast-neural-style/saved-models/udnie.pth --output-image /Users/DOVAN/Desktop/ --cuda 0
Traceback (most recent call last):
  File "neural_style/neural_style.py", line 210, in <module>
    main()
  File "neural_style/neural_style.py", line 206, in main
    stylize(args)
  File "neural_style/neural_style.py", line 135, in stylize
    content_image = Variable(utils.preprocess_batch(content_image), volatile=True)
  File "/Users/DOVAN/deeprely/fast-neural-style/neural_style/utils.py", line 59, in preprocess_batch
    (r, g, b) = torch.chunk(batch, 3)
ValueError: need more than 2 values to unpack

I think this may be come from the Function parameters' error

**Comment by abhiskk** [comment]
@dovanchan what environment are you running this on, I just tested this implementation on python 2.7, on OSX and everything works well.

**Comment by dovanchan** [comment]
python2.7 on OSX 0.12.5   The same as you~

**Comment by dovanchan** [comment]
I am also used conda install pytorch ~

**Comment by abhiskk** [comment]
Are you sure you didn't edit anything, can you try re-cloning the repository and running it again, it should be working. Another option is to try it in python 3, if it fails in that also then something weird is happening. Also are you using `--cuda 1` while running the stylizing code, pytorch's GPU version on OSX can misbehave.

**Comment by dovanchan** [comment]
![image](https://user-images.githubusercontent.com/26133721/27513714-de2d1170-59a3-11e7-9110-60bd0d451a83.png)

This is my enviroment,I dont have change any setting,the same as you(python2.7 --cuda 0 ) I think may be because I am using the latest pytorch version?

**Comment by abhiskk** [comment]
yes that could be an issue, don't use the master version of pytorch right now, it's unstable I think because they are implementing numpy type indexing. Are you using this command to install pytorch:
`conda install pytorch torchvision -c soumith ` ?

**Comment by dovanchan** [comment]
Yes,I am using _conda install pytorch torchvision -c soumith_ ~

**Comment by abhiskk** [comment]
Please follow the following steps accurately, use the default images in the repository for stylizing. I just followed the steps listed below one by one and was able to run it successfully.

- Create new conda environment: `conda create --name fnstest python=2.7`
- Activate environment: `source activate fnstest`
- Install pytorch on OSX: `conda install pytorch torchvision -c soumith`
- Clone repository: `git clone https://github.com/abhiskk/fast-neural-style.git`
- Go inside the directory: `cd fast-neural-style/`
- Download pre-trained models using the command: `./download_styling_models.sh`
- Run the command: 
`python neural_style/neural_style.py eval --content-image images/content-images/amber.jpg --model saved-models/mosaic.pth --output-image stylized_amber.jpg --cuda 0`
- Open image `stylized_amber.jpg`

**Comment by dovanchan** [comment]
I found the real problem now,
When I run the step that you offer,It will be successful;
But when I try a new content image,I got the error:


```
(fnstest) Dovan-Rmbp:fast-neural-style DOVAN$ time python neural_style/neural_style.py eval --content-image images/content-images/image1.jpg --model saved-models/mosaic.pth --output-image stylized_amber.jpg --cuda 0
Traceback (most recent call last):
  File "neural_style/neural_style.py", line 210, in <module>
    main()
  File "neural_style/neural_style.py", line 206, in main
    stylize(args)
  File "neural_style/neural_style.py", line 135, in stylize
    content_image = Variable(utils.preprocess_batch(content_image), volatile=True)
  File "/Users/DOVAN/fast-neural-style/neural_style/utils.py", line 59, in preprocess_batch
    (r, g, b) = torch.chunk(batch, 3)
ValueError: need more than 2 values to unpack
```
Here is the image I used:
![image1](https://user-images.githubusercontent.com/26133721/27859468-6f7e00da-61ab-11e7-98d0-bf811dbfc92c.jpg)

**Comment by abhiskk** [comment]
The image that you shared is not in RGB format, you can convert it to RGB format using the following commands:
```python
from PIL import Image
content_image = Image.open('/path/to/image')
content_rgb_image = content_image.convert('RGB')
content_rgb_image.save('/path/to/output/image')
```

Then you can run the neural style on the new image. I have also attached the udnie styled version of the image.

Apologies for the late reply.
![issue_14_udnie](https://user-images.githubusercontent.com/3365035/28788012-7bd4c030-75d3-11e7-9115-6a0901cf0b18.jpg)

**Comment by abhiskk** [comment]
Closing the issue, please comment if similar problems resurface.
