### ISSUE TITLE
errors when loading the trained model

### ISSUE THREAD

**Issue by WERush** [abhiskk/fast-neural-style#18]
Hi, all

When I want to test the model, I load the state_dict(), but I got error information " KeyError: 'unexpected key "module.conv1.conv2d.weight" in state_dict' ".

Any idea?

Thanks.

**Comment by zyj0704033** [comment]
@WERush have you sovled the problem yet?

**Comment by abhiskk** [comment]
I just reran the script to stylize an image using a trained model and it worked perfectly, what problem are you facing exactly? The command I used was:

```bash
python neural_style/neural_style.py eval --content-image images/content-images/amber.jpg --model saved-models/mosaic.pth --output-image temp.jpg --cuda 0
```
