### ISSUE TITLE
some question in utils.py

### ISSUE THREAD

**Issue by poptree** [abhiskk/fast-neural-style#23]
```
def tensor_save_rgbimage(tensor, filename, cuda=False):
    if cuda:
        img = tensor.clone().cpu().clamp(0, 255).numpy()
    else:
        img = tensor.clone().clamp(0, 255).numpy()
    img = img.transpose(1, 2, 0).astype('uint8')
    img = Image.fromarray(img)
    img.save(filename)


def tensor_save_bgrimage(tensor, filename, cuda=False):
    (b, g, r) = torch.chunk(tensor, 3)
    tensor = torch.cat((r, g, b))
    tensor_save_rgbimage(tensor, filename, cuda)
```

it seems like if you use function tensor_save_bgrimage to save a tensor, it will first transform from BGR to RGB and then transform from RGB to GBR in the function tensor_save_rgbimage?

**Comment by abhiskk** [comment]
The `tensor_save_rgbimage` does a transpose, the `img` has a dimension `[H x W x C]` (H: height, W: width and C: channels). The transpose will bring the channel dimension to front, this is needed for using the `save` method.
