### ISSUE TITLE
train doesn't run: ValueError: not enough values to unpack (expected 3, got 2)

### ISSUE THREAD

**Issue by xaionaro** [abhiskk/fast-neural-style#25]
Hello. `train` doesn't run:

```
danusya@werewolf:~/fast-neural-style$ python3 neural_style/neural_style.py train --dataset ~/dataset/ --style-image ~/Caleido/Color_Kaleidoscope_2017-6-24_15141.png  --vgg-model-dir caleido_vgg --save-model-dir caleido_model --epochs 2 --cuda 0
/usr/local/lib/python3.5/dist-packages/torchvision/transforms/transforms.py:156: UserWarning: The use of the transforms.Scale transform is deprecated, please use transforms.Resize instead.
  "please use transforms.Resize instead.")
Traceback (most recent call last):
  File "neural_style/neural_style.py", line 210, in <module>
    main()
  File "neural_style/neural_style.py", line 204, in main
    train(args)
  File "neural_style/neural_style.py", line 50, in train
    style = utils.preprocess_batch(style)
  File "/home/danusya/fast-neural-style/neural_style/utils.py", line 59, in preprocess_batch
    (r, g, b) = torch.chunk(batch, 3)
ValueError: not enough values to unpack (expected 3, got 2)
```

**Comment by achaiah** [comment]
Are you using png images?  I ran into this too and found out that this project can only handle jpg.

**Comment by xaionaro** [comment]
Yep. Ok, thanks, I'll try without png.

**Comment by abhiskk** [comment]
As @xaionaro  pointed out this might be an issue with the format of image, you can convert the image to relevant format using the following code:

```python
from PIL import Image
content_image = Image.open('/path/to/image')
content_rgb_image = content_image.convert('RGB')
content_rgb_image.save('/path/to/output/image')
```

**Comment by achaiah** [comment]
@abhiskk  - Actually, it would be helpful if this code was incorporated into the project so people can use any type of image. The current error: `ValueError: not enough values to unpack (expected 3, got 2)` is completely misleading.

@xaionaro - if you want a quick way to convert all `png` into `jpg` just install `imagemagick` and do: `mogrify -format jpg *.png`

**Comment by abhiskk** [comment]
@achaiah - Point noted, I will try to incorporate this soon. Any PRs are also welcome. This code is also part of the [pytorch/examples](https://github.com/pytorch/examples/tree/master/fast_neural_style) repo, so if you want you can open a PR in that repo also.
